/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.local.projeto.individual.da.continuada;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author LEONARDOOLIVEIRALEAL
 */
public class Tela1 extends javax.swing.JFrame {
    //CPU
    Valores1 cpuMinimo = new Valores1();
    Valores1 cpuMaximo = new Valores1();
    Valores1 cpuMedia = new Valores1();
    
    //Disco
    Valores1 discoMinimo = new Valores1();
    Valores1 discoMaximo = new Valores1();
    Valores1 discoMedia = new Valores1();
    
    //Memória
    Valores1 memoriaMinimo = new Valores1();
    Valores1 memoriaMaximo = new Valores1();
    Valores1 memoriaMedia = new Valores1();
    
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prgBarra1 = new javax.swing.JProgressBar();
        lbTexto1 = new javax.swing.JLabel();
        lbMin1 = new javax.swing.JLabel();
        lbMax1 = new javax.swing.JLabel();
        lbMedia1 = new javax.swing.JLabel();
        prgBarra2 = new javax.swing.JProgressBar();
        lbTexto2 = new javax.swing.JLabel();
        lbMin2 = new javax.swing.JLabel();
        lbMax2 = new javax.swing.JLabel();
        lbMedia2 = new javax.swing.JLabel();
        prgBarra3 = new javax.swing.JProgressBar();
        lbTexto3 = new javax.swing.JLabel();
        lbMin3 = new javax.swing.JLabel();
        lbMax3 = new javax.swing.JLabel();
        lbMedia3 = new javax.swing.JLabel();
        btnAcao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        prgBarra1.setString("");
        prgBarra1.setStringPainted(true);

        lbTexto1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTexto1.setText("CPU");

        lbMin1.setText("Mínimo: 0");

        lbMax1.setText("Máximo: 0");

        lbMedia1.setText("Média: 0");

        prgBarra2.setString("");
        prgBarra2.setStringPainted(true);

        lbTexto2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTexto2.setText("Disco");

        lbMin2.setText("Mínimo: 0");

        lbMax2.setText("Máximo: 0");

        lbMedia2.setText("Média: 0");

        prgBarra3.setString("");
        prgBarra3.setStringPainted(true);

        lbTexto3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTexto3.setText("Memória");

        lbMin3.setText("Mínimo: 0");

        lbMax3.setText("Máximo: 0");

        lbMedia3.setText("Média: 0");

        btnAcao.setText("Fazer Leitura dos Dados");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTexto2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTexto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAcao)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMin3)
                                .addGap(40, 40, 40)
                                .addComponent(lbMax3)
                                .addGap(40, 40, 40)
                                .addComponent(lbMedia3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prgBarra3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                                .addComponent(prgBarra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prgBarra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTexto3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbMin2)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbMax2)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbMedia2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(lbMin1)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbMax1)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbMedia1))))
                        .addGap(144, 219, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbTexto1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAcao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prgBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMin1)
                    .addComponent(lbMax1)
                    .addComponent(lbMedia1))
                .addGap(45, 45, 45)
                .addComponent(lbTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMin2)
                    .addComponent(lbMax2)
                    .addComponent(lbMedia2))
                .addGap(45, 45, 45)
                .addComponent(lbTexto3)
                .addGap(18, 18, 18)
                .addComponent(prgBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMin3)
                    .addComponent(lbMax3)
                    .addComponent(lbMedia3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    Integer i = 1;
    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        
        // Gerando dados aleatórios
        Double numeroCpu = ThreadLocalRandom.current().nextDouble(1,100);
        Double numeroDisco = ThreadLocalRandom.current().nextDouble(1,100);
        Double numeroMemoria = ThreadLocalRandom.current().nextDouble(1,16);
        if (i == 1) {
/*---------------------------------------------------------------------------------------------------*/
            cpuMinimo.utilizacao = numeroCpu;
            cpuMaximo.utilizacao = numeroCpu;
            cpuMedia.utilizacao = numeroCpu;
            
            // Inserin dados da CPU
            lbMin1.setText(String.format("Mínimo: %.2f%%", cpuMinimo.utilizacao));
            lbMax1.setText(String.format("Máximo: %.2f%%", cpuMaximo.utilizacao));
            lbMedia1.setText(String.format("Média: %.2f%%", (cpuMedia.utilizacao/i)));
                
            prgBarra1.setValue(numeroCpu.intValue());
            prgBarra1.setString(String.format("Uso de CPU: %.2f%%", numeroCpu));
/*---------------------------------------------------------------------------------------------------*/            
            discoMinimo.utilizacao = numeroDisco;
            discoMaximo.utilizacao = numeroDisco;
            discoMedia.utilizacao = numeroDisco;
            
            // Inserin dados do Disco
            lbMin2.setText(String.format("Mínimo: %.2f%%", discoMinimo.utilizacao));
            lbMax2.setText(String.format("Máximo: %.2f%%", discoMaximo.utilizacao));
            lbMedia2.setText(String.format("Média: %.2f%%", (discoMedia.utilizacao/i)));
                
            prgBarra2.setValue(numeroDisco.intValue());
            prgBarra2.setString(String.format("Uso de Disco: %.2f%%", numeroDisco));
/*---------------------------------------------------------------------------------------------------*/                
            memoriaMinimo.utilizacao = numeroMemoria;
            memoriaMaximo.utilizacao = numeroMemoria;
            memoriaMedia.utilizacao = numeroMemoria;
            
            // Inserin dados da Memória
            lbMin3.setText(String.format("Mínimo: %.1fGB", memoriaMinimo.utilizacao));
            lbMax3.setText(String.format("Máximo: %.1fGB", memoriaMaximo.utilizacao));
            lbMedia3.setText(String.format("Média: %.1fGB", memoriaMedia.utilizacao/i));
                
            Double memoriaPorcentagem = (numeroMemoria * 100) / 16;                
            prgBarra3.setValue(memoriaPorcentagem.intValue());
            prgBarra3.setString(String.format("Uso de Memória: %.1fGB", numeroMemoria));
        }
/*---------------------------------------------------------------------------------------------------*/
        else{        
            if (cpuMinimo.utilizacao >= numeroCpu) {
                cpuMinimo.utilizacao = numeroCpu;
            }
            if (cpuMaximo.utilizacao <= numeroCpu) {
                cpuMaximo.utilizacao = numeroCpu;
            }
            cpuMedia.utilizacao = (cpuMedia.utilizacao + numeroCpu);
            
            // Inserin dados da CPU
            lbMin1.setText(String.format("Mínimo: %.2f%%", cpuMinimo.utilizacao));
            lbMax1.setText(String.format("Máximo: %.2f%%", cpuMaximo.utilizacao));
            lbMedia1.setText(String.format("Média: %.2f%%", (cpuMedia.utilizacao/i)));
                
            prgBarra1.setValue(numeroCpu.intValue());
            prgBarra1.setString(String.format("Uso de CPU: %.2f%%", numeroCpu));    
/*---------------------------------------------------------------------------------------------------*/        
            if (discoMinimo.utilizacao >= numeroDisco) {
                discoMinimo.utilizacao = numeroDisco;
            }
            if (discoMaximo.utilizacao <= numeroDisco) {
                discoMaximo.utilizacao = numeroDisco;
            }
            discoMedia.utilizacao = (discoMedia.utilizacao + numeroDisco);
            
            // Inserin dados do Disco
            lbMin2.setText(String.format("Mínimo: %.2f%%", discoMinimo.utilizacao));
            lbMax2.setText(String.format("Máximo: %.2f%%", discoMaximo.utilizacao));
            lbMedia2.setText(String.format("Média: %.2f%%", (discoMedia.utilizacao/i)));
                
            prgBarra2.setValue(numeroDisco.intValue());
            prgBarra2.setString(String.format("Uso de Disco: %.2f%%", numeroDisco));    
/*---------------------------------------------------------------------------------------------------*/
            Double memoriaMin = memoriaMinimo.utilizacao;
            if (memoriaMin >= numeroMemoria) {
                memoriaMinimo.utilizacao = numeroMemoria;
            }
            Double memoriaMax = memoriaMaximo.utilizacao;
            if (memoriaMax <= numeroMemoria) {
                memoriaMaximo.utilizacao = numeroMemoria;
            }
            memoriaMedia.utilizacao = (memoriaMedia.utilizacao + numeroMemoria);
            
            // Inserin dados da Memória
            lbMin3.setText(String.format("Mínimo: %.1fGB", memoriaMinimo.utilizacao));
            lbMax3.setText(String.format("Máximo: %.1fGB", memoriaMaximo.utilizacao));
            lbMedia3.setText(String.format("Média: %.1fGB", memoriaMedia.utilizacao/i));
                
            Double memoriaPorcentagem = (numeroMemoria * 100) / 16;                
            prgBarra3.setValue(memoriaPorcentagem.intValue());
            prgBarra3.setString(String.format("Uso de Memória: %.1fGB", numeroMemoria));
        }
        i++;
    }//GEN-LAST:event_btnAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JLabel lbMax1;
    private javax.swing.JLabel lbMax2;
    private javax.swing.JLabel lbMax3;
    private javax.swing.JLabel lbMedia1;
    private javax.swing.JLabel lbMedia2;
    private javax.swing.JLabel lbMedia3;
    private javax.swing.JLabel lbMin1;
    private javax.swing.JLabel lbMin2;
    private javax.swing.JLabel lbMin3;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JLabel lbTexto3;
    private javax.swing.JProgressBar prgBarra1;
    private javax.swing.JProgressBar prgBarra2;
    private javax.swing.JProgressBar prgBarra3;
    // End of variables declaration//GEN-END:variables
}
